version: '3'
services:

  postgres:
    image: timescale/timescaledb:latest-pg12
    ports:
      - "50000:5432"
    volumes:
      - lusankya_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lusankya

  postgres_test:
    image: timescale/timescaledb:latest-pg12
    ports:
      - "60000:5432"
    volumes:
      - lusankya_postgres_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lusankya_test

volumes:
  lusankya_postgres:
  lusankya_postgres_test: