x-rds-image: &rds-image
  image: mysql:8.0

x-rds-env: &rds-env
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: mysqluser
  MYSQL_PASSWORD: mysqlpassword


services:
  fuli_mysql:
    <<: *rds-image
    ports:
      - "6000:3306"
    volumes:
      - fuli_volume:/var/lib/mysql
    environment:
      <<: *rds-env
      MYSQL_DATABASE: fuli

  fuli_mysql_dev:
    <<: *rds-image
    ports:
      - "6001:3306"
    volumes:
      - fuli_volume_dev:/var/lib/mysql
    environment:
      <<: *rds-env
      MYSQL_DATABASE: fuli_dev

  fuli_mysql_test:
    <<: *rds-image
    ports:
      - "6002:3306"
    volumes:
      - fuli_volume_test:/var/lib/mysql
    environment:
      <<: *rds-env
      MYSQL_DATABASE: fuli_test


volumes:
  fuli_volume:
  fuli_volume_dev:
  fuli_volume_test: